// jeky/dealabs/models/Comment.kt
package jeky.dealabs.models

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Data class representing a user's comment on a post.
 * Comments will be stored in a subcollection under each post.
 */
data class Comment(
    @DocumentId // Automatically maps the Firestore document ID to this property
    val id: String = "", // Unique ID for the comment, usually generated by Firestore
    val userId: String = "", // ID of the user who made the comment
    val username: String = "Anonymous", // Display name of the user who made the comment
    val textContent: String = "", // The text content of the comment
    @ServerTimestamp // Firestore will automatically populate this with the server's timestamp
    val timestamp: Date? = null // When the comment was created
)