// jeky/dealabs/models/Post.kt
package jeky.dealabs.models

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Data class representing a user's post in the social feed.
 * Fields are set up to be easily mapped to and from Firestore documents.
 */
data class Post(
    @DocumentId // Automatically maps the Firestore document ID to this property
    val id: String = "", // Unique ID for the post, usually generated by Firestore
    val userId: String = "", // ID of the user who created the post
    val username: String = "Anonymous", // Display name of the user who created the post
    val textContent: String? = null, // The main text content of the post
    val imageUrl: String? = null, // URL of the image, if an image is attached to the post
    @ServerTimestamp // Firestore will automatically populate this with the server's timestamp
    val timestamp: Date? = null, // When the post was created
    val profileImage: String? = null, // Base64 encoded profile image
    val likes: List<String> = emptyList() // List of user IDs who have liked this post
)